#!/bin/bash
# Funcion potencia de dos numeros

function potencia() {
local p
local i
i=1
p=1
while [ $i -le $2 ]; do
	p=$((p * $1))
	i=$((i + 1))
done
return $p
}

read -p "Digite la base: " b
read -p "Digite el exponente: " e
potencia $b $e
echo "$b ^ $e = " $?
